gravity_compensation_controller:
  type: open_manipulator_controllers/GravityCompensationController
  joint_names:
    - joint1
    - joint2
    - joint3
    - gripper

  root_link: world
  tip_link: link5
